import Foundation

nonisolated struct JourneyContentItem: Identifiable, Sendable {
    let id: UUID
    let title: String
    let subtitle: String
    let icon: String
    let detail: String
    let synopsis: String
    let duration: String
    let chapters: Int
    let prayers: Int
    let reads: Int
    let reflections: Int
    let difficulty: String

    static let scriptureItems: [JourneyContentItem] = [
        JourneyContentItem(id: UUID(), title: "Genesis to Revelation", subtitle: "Read through the Bible in 365 days", icon: "book.closed.fill", detail: "A daily reading plan that takes you through the entire Bible over the course of a year.", synopsis: "Embark on a transformative 365-day journey through the entire Bible. From the creation story in Genesis to the prophetic visions of Revelation, each day brings a carefully curated reading that builds upon the last. You'll witness God's covenant with Abraham, walk with Moses through the wilderness, sing with David, gain wisdom from Solomon, and ultimately encounter the life-changing message of Christ and the early church.", duration: "365 days", chapters: 52, prayers: 1240, reads: 8750, reflections: 430, difficulty: "Committed"),
        JourneyContentItem(id: UUID(), title: "Psalms of Comfort", subtitle: "30 psalms for difficult seasons", icon: "text.book.closed.fill", detail: "A curated collection of psalms that bring peace and reassurance.", synopsis: "When life feels heavy and uncertain, the Psalms offer a sanctuary of words that speak directly to the weary heart. This 30-day journey walks you through carefully selected psalms — each chosen for its power to comfort, restore hope, and remind you that you are never alone. Includes guided reflections and breath prayers for each psalm.", duration: "30 days", chapters: 30, prayers: 890, reads: 3200, reflections: 670, difficulty: "Gentle"),
        JourneyContentItem(id: UUID(), title: "Proverbs of Wisdom", subtitle: "Daily wisdom for modern life", icon: "scroll.fill", detail: "One proverb a day to guide your decisions and character.", synopsis: "Ancient wisdom meets modern challenges. Each day presents a proverb paired with a contemporary reflection, helping you apply timeless truths to everyday decisions — from relationships and finances to integrity and speech. This journey cultivates discernment and grounds your daily walk in practical, Spirit-led wisdom.", duration: "31 days", chapters: 31, prayers: 540, reads: 2100, reflections: 310, difficulty: "Approachable"),
        JourneyContentItem(id: UUID(), title: "The Gospels", subtitle: "Walk with Jesus through all four accounts", icon: "star.fill", detail: "Experience the life, teachings, death, and resurrection of Christ.", synopsis: "Experience the life of Jesus through four distinct yet harmonious perspectives. Matthew reveals the promised King, Mark the suffering Servant, Luke the compassionate Healer, and John the divine Word made flesh. This journey weaves all four accounts into a rich tapestry, with daily prayers and reflections that bring you face to face with the person of Christ.", duration: "90 days", chapters: 89, prayers: 2100, reads: 5400, reflections: 890, difficulty: "Moderate"),
        JourneyContentItem(id: UUID(), title: "Letters of Paul", subtitle: "Faith, hope, and love in the epistles", icon: "envelope.open.fill", detail: "Journey through Paul's letters to the early churches.", synopsis: "Step into the world of the early church through Paul's passionate letters. From the theological depths of Romans to the intimate encouragement of Philippians, each epistle reveals how the gospel transforms communities and individual hearts. Includes historical context, theological insights, and practical applications for your faith today.", duration: "60 days", chapters: 48, prayers: 1560, reads: 4200, reflections: 520, difficulty: "Moderate"),
    ]

    static let prayerItems: [JourneyContentItem] = [
        JourneyContentItem(id: UUID(), title: "Morning Offerings", subtitle: "Start each day surrendered", icon: "sun.horizon.fill", detail: "A collection of morning prayers to begin each day in devotion.", synopsis: "Begin each morning with intention and surrender. This collection of 30 morning prayers guides you through themes of gratitude, trust, and purpose — helping you offer the first moments of your day to God. Each prayer is paired with a short scripture and a centering breath exercise to ground your spirit before the day unfolds.", duration: "30 days", chapters: 30, prayers: 2400, reads: 980, reflections: 450, difficulty: "Gentle"),
        JourneyContentItem(id: UUID(), title: "Evening Vespers", subtitle: "Close the day in gratitude", icon: "moon.stars.fill", detail: "Reflective evening prayers to end your day peacefully.", synopsis: "As the day draws to a close, find stillness in these ancient-inspired evening prayers. Each vesper includes a prayer of thanksgiving, an examen reflection to review your day with grace, and a peaceful benediction to carry into sleep. Rooted in the monastic tradition of evening worship.", duration: "30 days", chapters: 30, prayers: 1800, reads: 720, reflections: 600, difficulty: "Gentle"),
        JourneyContentItem(id: UUID(), title: "Prayers for Others", subtitle: "Intercessory prayer guides", icon: "person.2.fill", detail: "Structured prayers for lifting up family, friends, and the world.", synopsis: "Expand your prayer life beyond yourself with this structured intercessory guide. Each day focuses on a different circle of care — family, friends, community, nation, and world — with specific prompts and scriptures to fuel your prayers. Learn to intercede with boldness and compassion.", duration: "21 days", chapters: 21, prayers: 3200, reads: 560, reflections: 340, difficulty: "Approachable"),
        JourneyContentItem(id: UUID(), title: "Prayers of Lament", subtitle: "Honest words in hard times", icon: "cloud.rain.fill", detail: "Prayers for seasons of grief, doubt, and struggle.", synopsis: "In seasons of suffering, silence can feel unbearable. These prayers give voice to your pain, following the biblical tradition of lament — honest cries to God that lead from anguish toward hope. Drawing from the Psalms and the prophets, this journey validates your grief and gently holds space for healing.", duration: "14 days", chapters: 14, prayers: 1100, reads: 420, reflections: 280, difficulty: "Deep"),
        JourneyContentItem(id: UUID(), title: "Thanksgiving Prayers", subtitle: "Cultivate a grateful heart", icon: "leaf.fill", detail: "Prayers of praise and thanks for every blessing.", synopsis: "Gratitude transforms everything it touches. This 21-day journey rewires your heart toward thankfulness through daily prayers of praise, gratitude journaling prompts, and scriptures that celebrate God's faithfulness. Watch as a posture of thanksgiving reshapes how you see the world.", duration: "21 days", chapters: 21, prayers: 1600, reads: 840, reflections: 520, difficulty: "Gentle"),
    ]

    static let journeyItems: [JourneyContentItem] = [
        JourneyContentItem(id: UUID(), title: "40 Days of Faith", subtitle: "A transformative spiritual journey", icon: "flame.fill", detail: "A 40-day guided experience to deepen your faith walk.", synopsis: "Inspired by the biblical significance of 40 days — from Noah's flood to Jesus in the wilderness — this journey invites you into a season of deep spiritual transformation. Each day combines scripture study, guided prayer, and a faith challenge that stretches you beyond comfort into genuine trust. By day 40, your faith will have new roots.", duration: "40 days", chapters: 40, prayers: 3600, reads: 4800, reflections: 1200, difficulty: "Committed"),
        JourneyContentItem(id: UUID(), title: "The Fruits of the Spirit", subtitle: "9 weeks of character formation", icon: "tree.fill", detail: "Explore love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control.", synopsis: "Spend nine transformative weeks cultivating the character of Christ. Each week focuses on one fruit of the Spirit from Galatians 5:22-23, with daily readings, real-world practices, and reflective prayers. From the radical love of agape to the quiet strength of self-control, watch the Spirit reshape your character from the inside out.", duration: "63 days", chapters: 63, prayers: 4200, reads: 5600, reflections: 1800, difficulty: "Moderate"),
        JourneyContentItem(id: UUID(), title: "Finding Your Purpose", subtitle: "Discover God's plan for you", icon: "compass.drawing", detail: "A 21-day journey to uncover your unique calling.", synopsis: "You were created with intention. This 21-day guided journey helps you discover your unique gifts, passions, and calling through scripture study, personality reflection, and prayerful listening. Each day peels back another layer, revealing how God has been preparing you for a purpose only you can fulfill.", duration: "21 days", chapters: 21, prayers: 1400, reads: 2100, reflections: 840, difficulty: "Approachable"),
        JourneyContentItem(id: UUID(), title: "The Beatitudes", subtitle: "Living the Sermon on the Mount", icon: "mountain.2.fill", detail: "8 weeks studying and applying the Beatitudes.", synopsis: "Jesus' most famous sermon begins with eight radical blessings that turn the world's values upside down. Over eight weeks, explore each Beatitude in depth — its historical context, its counter-cultural challenge, and its promise. Includes daily scripture, commentary from the early church fathers, and practical exercises to live these blessings.", duration: "56 days", chapters: 56, prayers: 2800, reads: 4500, reflections: 1100, difficulty: "Moderate"),
    ]

    static let insightItems: [JourneyContentItem] = [
        JourneyContentItem(id: UUID(), title: "Bookmarked Verses", subtitle: "12 saved verses", icon: "bookmark.fill", detail: "Your personally saved scripture passages.", synopsis: "A personal treasury of scripture that has spoken to your heart. Revisit your bookmarked verses organized by theme, date saved, and the emotional context in which they found you. Each verse is preserved with your notes and the moment it became meaningful to you.", duration: "Ongoing", chapters: 12, prayers: 180, reads: 540, reflections: 96, difficulty: "Personal"),
        JourneyContentItem(id: UUID(), title: "Journal Entries", subtitle: "8 reflections this month", icon: "note.text", detail: "Your spiritual journal and personal reflections.", synopsis: "Your sacred space for honest reflection. Review your journal entries — the prayers whispered, the lessons learned, and the moments of clarity. Writing is a form of worship, and this collection is your ongoing conversation with God, preserved for revisiting in every season.", duration: "Ongoing", chapters: 8, prayers: 64, reads: 120, reflections: 240, difficulty: "Personal"),
        JourneyContentItem(id: UUID(), title: "Prayer Answers", subtitle: "Testimonies of faithfulness", icon: "checkmark.seal.fill", detail: "Prayers that have been answered — reminders of God's faithfulness.", synopsis: "A living memorial of God's faithfulness. Each answered prayer recorded here serves as a stone of remembrance — proof that God hears, God moves, and God is faithful. Revisit these testimonies whenever doubt creeps in and let them reignite your trust.", duration: "Ongoing", chapters: 5, prayers: 320, reads: 90, reflections: 150, difficulty: "Personal"),
    ]

    static func items(for category: JourneyCategory) -> [JourneyContentItem] {
        switch category {
        case .scripture: return scriptureItems
        case .prayerLibrary: return prayerItems
        case .guidedJourneys: return journeyItems
        case .savedInsights: return insightItems
        }
    }
}
